spring:
  application:
    name: complaint-hub
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/complaints_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
geo:
  api:
    url: http://ip-api.com/json/%s
springdoc:
  server:
    base-url: https://ubiquitous-funicular-v644xg9jrqj2p5wx-8080.app.github.dev